using Microsoft.AspNetCore.Mvc;
using Firebase.Database;
using Alpha_API.Models;
using Firebase.Database.Query;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Alpha_API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]

    [Authorize(Roles = "admin,staff")]
    public class ImportEquipmentController : ControllerBase
    {
        private readonly FirebaseClient _firebaseClient;

        public ImportEquipmentController()
        {
            _firebaseClient = new FirebaseClient("https://sgm-management-c98cd-default-rtdb.firebaseio.com/");
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<object>>> GetImportEquipments()
        {
            var importEquipmentsTask = _firebaseClient
                .Child("ImportEquipment")
                .OnceAsync<ImportEquipment>();
            var equipmentsTask = _firebaseClient
                .Child("equipment")
                .OnceAsync<Equipment>();

            await Task.WhenAll(importEquipmentsTask, equipmentsTask);

            var importEquipments = importEquipmentsTask.Result;
            var equipments = equipmentsTask.Result.ToDictionary(e => e.Key, e => new { e.Object.EquipmentCode, e.Object.EquipmentName });

            var importEquipmentList = importEquipments
                .Select(import => new
                {
                    ImportEquipmentId = import.Key,
                    ImportDate = import.Object.ImportDate,
                    ImportQuantity = import.Object.ImportQuantity,
                    ImportPrice = import.Object.ImportPrice,
                    ImportTotalPrice = import.Object.ImportTotalPrice,
                    EquipmentId = import.Object.EquipmentId,
                    EquipmentCode = equipments.GetValueOrDefault(import.Object.EquipmentId)?.EquipmentCode ?? "Unknown",
                    EquipmentName = equipments.GetValueOrDefault(import.Object.EquipmentId)?.EquipmentName ?? "Unknown",
                    Importer = import.Object.Importer
                })
                .OrderByDescending(x => x.ImportDate.Year)
                .ThenByDescending(x => x.ImportDate.Month)
                .ThenByDescending(x => x.ImportDate.Date);

            return Ok(importEquipmentList);
        }

        // POST: api/ImportEquipment
        [HttpPost]
        public async Task<ActionResult<ImportEquipment>> PostImportEquipment([FromBody] ImportEquipment importEquipment)
        {
            if (importEquipment == null)
            {
                return BadRequest(new { message = "Invalid import equipment data." });
            }

            var vietnamTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time"); // "SE Asia Standard Time" for UTC+7
            DateTime vietnamTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, vietnamTimeZone);

            importEquipment.ImportDate = importEquipment.MapDateTimeToCustomFormat(vietnamTime);

            // Calculate ImportTotalPrice if it wasn't provided (assuming Quantity * Import Price per item if needed)
            // You might want to adjust this logic based on your specific requirements.
            if (importEquipment.ImportTotalPrice == 0 && importEquipment.ImportQuantity > 0)
            {
                importEquipment.ImportTotalPrice = importEquipment.ImportQuantity * importEquipment.ImportPrice;
            }

            // Add ImportEquipment to Firebase
            var result = await _firebaseClient
                .Child("ImportEquipment")
                .PostAsync(importEquipment);

            // Set ImportEquipmentId to the key generated by Firebase
            importEquipment.ImportEquipmentId = result.Key;

            return CreatedAtAction(nameof(GetImportEquipments), new { id = importEquipment.ImportEquipmentId }, importEquipment);
        }

        [HttpDelete("deleteAllImportEquipment")]
        public async Task<IActionResult> DeleteAllImportEquipments()
        {
            // Lấy danh sách tất cả import equipment
            var importEquipments = await _firebaseClient
                .Child("ImportEquipment")
                .OnceAsync<ImportEquipment>();

            if (importEquipments == null || !importEquipments.Any())
            {
                return NotFound(new { message = "Không có thiết bị nhập khẩu nào trong hệ thống để xóa." });
            }

            // Duyệt qua từng import equipment và xóa nó
            foreach (var importEquipment in importEquipments)
            {
                await _firebaseClient
                    .Child("ImportEquipment")
                    .Child(importEquipment.Key)
                    .DeleteAsync();
            }

            return Ok(new { message = "Tất cả thiết bị nhập khẩu đã được xóa thành công." });
        }

    }
}
